[phases.setup]
nixPkgs = ["jdk17"]

[phases.install]
cmds = ["cd backend && mvn clean package -DskipTests"]

[phases.build]
cmds = ["cd backend && mvn package -DskipTests"]

[start]
cmd = "cd backend && java -jar target/ecovive-backend-1.0.0.jar"
