server:
  port: ${PORT:8080}

spring:
  application:
    name: ecovive-backend
  
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  
  h2:
    console:
      enabled: true
  
  security:
    jwt:
      secret: ecovive_jwt_secret_key_2024_very_secure_256_bits
      expiration: 86400000

logging:
  level:
    com.ecovive: INFO
    org.springframework: WARN
    org.hibernate: WARN